# Site settings
title: Luidy Naves
header-img: img/home.jpg
email: luidymorais@gmail.com
subtitle: "Um pouco do meu conhecimento tecnológico"
description: "Um pouco do meu conhecimento tecnológico"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.luidynaves.com" # the base hostname & protocol for your site
twitter_username: luidymorais
github_username:  luidymorais
linkedin_pagename: luidy

defaults:
  -
    scope:
      path: ""
    values:
      lang: pt
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en      
  -

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title
paginate: 6
exclude: ["Readme.md", "Gemfile", "Gemfile.lock", "CNAME", "_followup"]